version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: org.xhtmlrenderer:flying-saucer-pdf-itext5
    versions:
    - 9.1.20
  - dependency-name: org.xhtmlrenderer:flying-saucer-core
    versions:
    - 9.1.20
  - dependency-name: commons-net:commons-net
    versions:
    - 3.7.2
  - dependency-name: org.springframework:spring-core
    versions:
    - 5.3.0
