info:
  app:
    name: '@project.artifactId@'
    description: '@project.description@'
  build:
    groupId: '@project.groupId@'
    artifact: '@project.artifactId@'
    name: '@project.name@'
    version: '@project.version@'
    encoding: '@project.build.sourceEncoding@'
